# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\"O\n\x0cUserDataDict\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"N\n\x0e\x44\x42UserResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1b\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\r.UserDataDict2g\n\x07UserMgt\x12.\n\nCreateUser\x12\r.UserDataDict\x1a\x0f.DBUserResponse\"\x00\x12,\n\x08ReadUser\x12\r.UserDataDict\x1a\x0f.DBUserResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERDATADICT._serialized_start=22
  _USERDATADICT._serialized_end=101
  _DBUSERRESPONSE._serialized_start=103
  _DBUSERRESPONSE._serialized_end=181
  _USERMGT._serialized_start=183
  _USERMGT._serialized_end=286
# @@protoc_insertion_point(module_scope)
